### ISSUE TITLE
Key things missing to view locally

### ISSUE THREAD

**Issue by markcmiller86** [betterscientificsoftware/PSIP-Tools#4]
This site is missing some things to view content locally

- frontmatter in all .md files
- github-supported theme
- gemfile (to use bundle exec)
- no index.html is produced

All easily fixible and I am willing to do if ok with you

**Comment by curfman** [comment]
Hi Mark -- Thanks for pointing out these issues.  Yes, please fix when you have a chance.

**Comment by markcmiller86** [comment]
Well, I think I went down a wrong path here. I was not able to view locally with typicall `jekyll serve` or `bundle exec jekyll serve` commands. I would **not** wind up with any html content in the _site dir and there would be no index.html there. But, simply adding the Gemfile seems to have fixed that. So, that is all I wound up doing. Oh, and there was a newline missing from the _config.yml file too. That also may have been effecting things.
